### ISSUE TITLE
Default selection missing when component initialized with with a valid schedule

### ISSUE THREAD

**Issue by Wu-Jing** [rvalenciano/ngx-cron-jobs#14]
Steps to reproduce:
1. Using the app in this repo, before running the app, change freq in AppComponent to '0 * * * * ?'  (Quartz) and change default service to Quartz
2. Run the app, you can see the Set frequency (ngModel) is minute. 
3. Click on minute and select day
4. Issue: there is no the default value selected for fields after "at"

**Comment by Wu-Jing** [comment]
Adding more details to step 4: since the default value is not populated, especially for non mutiple choice view, the user will see the first value in each field, but that value is actually not selected,  as you can see the generate cron value is still the cron for minute. Pr created against yp2 repo.

**Comment by rvalenciano** [comment]
@Wu-Jing I merged the PR from yp2 repo, are we ok to close this?

**Comment by Wu-Jing** [comment]
Yep. I tried it and all works as expected. Thanks.
