### ISSUE TITLE
Select default value for week, month and year

### ISSUE THREAD

**Issue by WhistlerHusky** [rvalenciano/ngx-cron-jobs#3]
When I select "week", the default selection for weekday is empty.

but actually, it's 0 (Sunday). so I think it should display Sunday as default.

and month and year should be the same.  those default value look like 0, so if a user does not select the value, it cause an error.

**Comment by rvalenciano** [comment]
Hi, currently I'm refactoring a bit the library to a more appropriate format as library.  As part of the refactor I'll be doing this issue.

**Comment by yp2** [comment]
Fixed in this rewrite and refactor https://github.com/yp2/ngx-cron-jobs.
